
<?php
$this->headMeta()->appendHttpEquiv('Content-Type', 'text/html;charset=utf-8');
$this->headTitle()->setSeparator(' - ');
$this->headTitle('99d app');
echo $this->doctype(); ?>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
    <?php echo $this->headMeta(); ?>
    <?php echo $this->headTitle(); ?>
    <?php echo $this->headLink()->prependStylesheet($this->baseUrl().'/css/960.css'); ?>
    <?php echo $this->headLink()->prependStylesheet($this->baseUrl().'/css/site.css'); ?>
    <?php echo $this->jQuery();?>   
    <?php echo $this->headScript()->appendFile('/99d/public/js/jquery.isotope.js');  ?>

<script type="text/javascript">

            <?php if (!Zend_Registry::get('fbUser')) : ?>
            var newwindow;
            var intId;
            function login(){
                var  screenX    = typeof window.screenX != 'undefined' ? window.screenX : window.screenLeft,
                     screenY    = typeof window.screenY != 'undefined' ? window.screenY : window.screenTop,
                     outerWidth = typeof window.outerWidth != 'undefined' ? window.outerWidth : document.body.clientWidth,
                     outerHeight = typeof window.outerHeight != 'undefined' ? window.outerHeight : (document.body.clientHeight - 22),
                     width    = 500,
                     height   = 270,
                     left     = parseInt(screenX + ((outerWidth - width) / 2), 10),
                     top      = parseInt(screenY + ((outerHeight - height) / 2.5), 10),
                     features = (
                        'width=' + width +
                        ',height=' + height +
                        ',left=' + left +
                        ',top=' + top
                      );
     
                newwindow=window.open('<?php echo Zend_Registry::get('fbUrl'); ?>','Login_by_facebook',features);
     
                 if (window.focus) {newwindow.focus()}
                return false;
            }
     
            <?php endif; ?>
    </script>
</head>
<body>
    <div class="container_12">
            
       <div class="grid_12 fmenu">
    
                <a href="<?php echo $this->url(array('controller'=>'index','action'=>'index'),null,true);?>">99d Home</a> 
                <?php if (Zend_Registry::get('fbUser')) : ?>
                <a href="<?php echo Zend_Registry::get('fbUrl'); ?>"> 
                   <img src="http://static.ak.fbcdn.net/rsrc.php/z2Y31/hash/cxrz4k7j.gif" border="0">
                </a> Hello <?php echo $registry['fbuser_profile']['name']; ?>
                    <img src="https://graph.facebook.com/<?php echo Zend_Registry::get('fbUser'); ?>/picture">
                <a href="<?php echo $this->url(array('controller'=>'applications','action'=>'index'),null,true);?>">Your Applications</a>
                <?php else: ?>
                <a href="#" onclick="login();return false;">
                <img src="http://static.ak.fbcdn.net/rsrc.php/zB6N8/hash/4li2k73z.gif" border="0">
                </a>
                <?php endif; ?>
            </ul>
        
    </div><!-- end .header -->
            <?php echo $this->layout()->content; ?>
    </div> <!-- end container -->
</body>
</html>

